excluded:
  - Sources/Ghostty
  - ghostty
  - DerivedData
  - build

identifier_name:
  excluded:
    - id
    - up

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 500
  error: 600
