excluded:
  - Sources/Ghostty
  - ghostty
  - DerivedData
  - build

identifier_name:
  excluded:
    - id
    - up

type_body_length:
  warning: 450
  error: 550

file_length:
  warning: 650
  error: 750
